### PR TITLE
Geometry collection

### PR DESCRIPTION
**Pull request by rocky1138**

### CODE REVIEW

**Comment by ingalls** [comment]
Thanks for getting this PR cut, really good idea adding the geojson hint.

**Comment by ingalls** [comment]
Note: this is now published under the `@mapbox` namespace. 

The new version is: `@mapbox/geojson-rewind@0.4.0`

**Comment by rocky1138** [comment]
Sorry to be a weenie but I can't seem to install that package. `npm install @mapbox/geojson-rewind` gives me "'@mapbox/geojson-rewind' is not in the npm registry."

**Comment by bhousel** [comment]
Ah yeah I noticed this too.. it looks like it hasn't been published yet.

**Comment by ingalls** [comment]
@bhousel @rocky1138 sorry about that, forgot that newly namespaced packages were private by default. 

It is public now and you should be able to see it here: https://www.npmjs.com/package/@mapbox/geojson-rewind

**Pull request merged**
